### ISSUE TITLE
Mapview.content inset are not working as expected on 5.5.0

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native-ios#59] opened 2019-11-12 16:49 UTC
Hello, after the changes to the contentInset in 5.5.0 I don't understand how the content inset is used.

Example:

The mapview has a frame width of 300
I set contentInset.left to 100
I set contentInset.right to 50

I would expect that if I zoom to a square MGLRegionBound I would see it inset by 100 on the left and 50 on the right.

However this is not happening.

The mapView **FRAME** is shifted by those values, so the region bound is not respected.

I see the box 100 px from the left but only some pixel from the right.

Why is that?

It looks to me that the left inset is applied to shift the entire mapview frame and then the region bound is drawn.

Another example is this:

set left to 300px
right to 0px

I would expect to see the region attached to the border on the right, starting 300 px from the left.
Instead, the region is totally out of the screen.

Could you explain me if I understood the inset wrong or this is a bug due to https://github.com/mapbox/mapbox-gl-native/pull/15584 ? thanks

**Comment by racer1988** [comment] 2019-11-13 11:43
I provide here an example screen:

Happening:

![result](https://user-images.githubusercontent.com/1517398/68760826-09654b00-0613-11ea-9e04-c9ddb36d37f9.jpg)

**I would expect both my shape and its bounding box to  be inside the contentInset of the map.
Instead they are shifted. I believe this is a bug since using setCamera(withEdgeInset) instead seem to work** 

Expected:

![expected](https://user-images.githubusercontent.com/1517398/68760833-0b2f0e80-0613-11ea-8ed7-a1f309d1da9c.jpg)


What you can see here:

- A mapView attached to the superview edges
- a semi-transparent Cyan view on top of the mapview attached to the superview edges
- A red line representing the bounding box of the shape I am trying to display.
- the shape itself as a blueline

What am I doing:

1) Creating a example inset:

```
let insets = UIEdgeInsets(top: 200,
                            left: 1,
                            bottom: 300,
                            right: 200)
```

2) Setting the inset on the mapView

```
mapView.contentInset = insets
```

3) Updating the cyan view boundaries to match the inset:
**this for me is what I would expect to be the drawable area of the mapview**

```
debugTrailing.constant = mapView.contentInset.right
debugLeading.constant = mapView.contentInset.left
debugTop.constant = mapView.contentInset.top
debugBottom.constant = mapView.contentInset.bottom
```

4)  Display the feature on the map 

```
let box: MGLCoordinateBounds
// blabla magic to drar the coordinate bounds on one of my sources
```


5) zooming to this feature I prepared by updating the camera:
Note: I am not using a inset here, I want the map to respect the contentInset for that instead.
This is needed for me, as sometimes I center around a coordinate instead, I don't have bounds, and I can't provide edge insets to `mapView.fly(to: camera, withDuration: animated ? -1.0 : 0.0, completionHandler: nil)`

```
mapView.setVisibleCoordinateBounds(box,
                                           edgePadding: .zero,
                                           animated: animated,
                                           completionHandler: completionHandler)
```

**Comment by racer1988** [comment] 2019-11-13 14:57
Sorry for the triple post, but I would like to provide as much info as I can to be sure to get to the point:

Everything works fine if the EdgeInset are the same on top-bottom or left-right.
Then the content is inset correctly, and the mapview.center does not move.

As soon as there is a difference between top-bottom or left-right.... then the center of the map is not where i would expect it to be.

example:

let's take the frame of the Map

```
po mapView.frame
(0.0, 0.0, 375.0, 812.0)
```

Let's  apply a content Inset LEFT of width/2 = 187

The result should be that the center of the map is located on x at 375 + 187 
and the bounding box is displayed from the center of the screen to the right edge.

instead the bounding box starts at 375+ 187 + **187/2** and the right side of the bounding box is at
mapView.frame.width + **187**

This happens also if I use a camera animation by using  `mapView.cameraThatFitsCoordinateBounds(bounds)`

Does this mean that the inset moves the viewPort logically but does not shrink the viewport ?
Is the viewport always as big as the mapView.frame?
if yes, what is the entire point of the content inset?

**Comment by racer1988** [comment] 2019-11-13 15:54
Just verified that the content inset are working correctly when creating a camera around a point.
They are not working when the camera is created or set to fit a BoundingBox.

The reason seems to be that the camera to fit the bounding box is calculated correctly respecting the contentInset but then the camera center is calculated wrongly instead.

**Comment by RomainQuidet** [comment] 2019-12-11 10:57
I also have the same issue, setCenterCoordinate behave correctly with a contenInset, but setVisibleCoordinates does not...

**Comment by RomainQuidet** [comment] 2019-12-11 15:00
`diff --git a/src/mbgl/map/map.cpp b/src/mbgl/map/map.cpp
index 649e0e321e..e0f63bc0e8 100644
--- a/src/mbgl/map/map.cpp
+++ b/src/mbgl/map/map.cpp
@@ -182,13 +182,12 @@ CameraOptions cameraForLatLngs(const std::vector<LatLng>& latLngs, const Transfo
     // Calculate the bounds of the possibly rotated shape with respect to the viewport.
     ScreenCoordinate nePixel = {-INFINITY, -INFINITY};
     ScreenCoordinate swPixel = {INFINITY, INFINITY};
-    double viewportHeight = size.height;
     for (LatLng latLng : latLngs) {
         ScreenCoordinate pixel = transform.latLngToScreenCoordinate(latLng);
         swPixel.x = std::min(swPixel.x, pixel.x);
         nePixel.x = std::max(nePixel.x, pixel.x);
-        swPixel.y = std::min(swPixel.y, viewportHeight - pixel.y);
-        nePixel.y = std::max(nePixel.y, viewportHeight - pixel.y);
+        swPixel.y = std::min(swPixel.y, pixel.y);
+        nePixel.y = std::max(nePixel.y, pixel.y);
     }
     double width = nePixel.x - swPixel.x;
     double height = nePixel.y - swPixel.y;
@@ -212,21 +211,9 @@ CameraOptions cameraForLatLngs(const std::vector<LatLng>& latLngs, const Transfo
 
     // Calculate the center point of a virtual bounds that is extended in all directions by padding.
     ScreenCoordinate centerPixel = nePixel + swPixel;
-    ScreenCoordinate paddedNEPixel = {
-        padding.right() / minScale,
-        padding.top() / minScale,
-    };
-    ScreenCoordinate paddedSWPixel = {
-        padding.left() / minScale,
-        padding.bottom() / minScale,
-    };
-    centerPixel = centerPixel + paddedNEPixel - paddedSWPixel;
     centerPixel /= 2.0;
 
-    // CameraOptions origin is at the top-left corner.
-    centerPixel.y = viewportHeight - centerPixel.y;
-
-    return CameraOptions().withCenter(transform.screenCoordinateToLatLng(centerPixel)).withZoom(zoom);
+    return CameraOptions().withCenter(transform.screenCoordinateToLatLng(centerPixel)).withPadding(padding).withZoom(zoom);
 }
 
 CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, const EdgeInsets& padding, optional<double> bearing, optional<double> pitch) const {`

**Comment by RomainQuidet** [comment] 2019-12-11 15:03
Seems to me that `CameraOptions cameraForLatLngs(const std::vector<LatLng>& latLngs, const Transform& transform, const EdgeInsets& padding)` method in map.cpp is doing wrong geomatic computation.
By simplifying it, I manage to get a correct behavior with `setVisibleCoordinates` methods group.

**Comment by RomainQuidet** [comment] 2019-12-11 16:11
So the issue is locate in mbgl-core, which is on another repo now... What is the process here for a pull request ?

**Comment by racer1988** [comment] 2019-12-11 16:13
@RomainQuidet I would say  open a PR to the core repo and link this issue and say it's fixing it.

I guess tough the new change should not break the SDK tests here. 
Or maybe it should break it to show the behaviour is wrong ;) 

However If it is a core issue I guess similar problems should popup in the android and web sdks.

I wonder if the iOS layer on top of is also not reading the data wrong comign from the core

**Comment by RomainQuidet** [comment] 2019-12-16 16:47
PR sent, we'll see what's going on ;) My tests show a correct behavior of our app with this patch.

**Comment by racer1988** [comment] 2019-12-17 15:21
@RomainQuidet @astojilj I see the PR was merged!

When we can expect this in a SDK Release?

Thanks

**Comment by RomainQuidet** [comment] 2019-12-17 15:33
yes, really cool they accepted the correction. It's now on master branch of mapbox-gl-native submodule, it needs to be taken by iOS devs on this project. 
I don't know about the timing ... 5.6.0 is in beta state, I don't know if they are allowed to change it now.

**Comment by julianrex** [comment] 2019-12-17 16:50
This is awesome @RomainQuidet @racer1988 - thanks so much for submitting that PR, and thanks @astojilj for landing this in gl-native!

> When we can expect this in a SDK Release?

> I don't know about the timing ... 5.6.0 is in beta state, I don't know if they are allowed to change it now.

This will be in `5.7.0` which is due early February IIRC.

**Comment by chloekraw** [comment] 2019-12-17 16:55
Thanks for your help with this investigation @RomainQuidet @racer1988! The fix will also be available in pre-releases in January for you to test and confirm the issue is resolved. Expect an `alpha` release the 2nd week of January and a `beta` the 4th week of January. cc @zugaldia

**Closed** 2020-04-07 01:53 UTC
Labels: bug

**Comment by mfazekas** [comment] 2020-06-18 15:14
We're now facing a regression that might be caused by this fix when doing flyTo with edgePadding on ios:

See https://github.com/mapbox/mapbox-gl-native-ios/issues/198

I think that the cause is that when converting CameraOptions to MGLMapCamera edgePadding is ignored:

https://github.com/mapbox/mapbox-gl-native-ios/blob/a13921663715be33907a9c1bdb8e220a43e03a83/platform/ios/src/MGLMapView.mm#L4011-L4025


Before the fix in this pr edgePadding was not used in the C++ `CameraOptions` but center was adjusted accordingly, this was converted to `MGLMapCamera` but now that `CameraOptions` uses padding - `CameraOptions` to `MGLMapCamera` no longer works correctly when edge padding was used.

**Comment by zugaldia** [comment] 2020-06-18 19:26
@mfazekas thanks for the report. Could you open a separate ticket to track this potential regression?

**Comment by mfazekas** [comment] 2020-06-18 20:50
@zugaldia FYI there is issue #198 which is the regression.

**Comment by astojilj** [comment] 2020-07-14 16:44
@RomainQuidet do you have a proposal how to reconcile this with https://github.com/mapbox/mapbox-gl-native-ios/issues/198?

**Comment by RomainQuidet** [comment] 2020-07-16 07:50
Hi @astojilj I'm sorry I don't work on my customer's project involving mapbox anymore. Anyway if I have some free time I'll check both issues and the code.

**Comment by astojilj** [comment] 2020-07-17 06:01
> Hi @astojilj I'm sorry I don't work on my customer's project involving mapbox anymore. Anyway if I have some free time I'll check both issues and the code.

No worries, we'll fix it. Thanks again.
