### ISSUE TITLE
Fonts are not fetched from in-house tile server on Mapbox-iOS-SDK 6.2.0

### ISSUE THREAD

**Issue by behdaad** [mapbox/mapbox-gl-native-ios#450] opened 2020-09-16 16:19 UTC
**Update:** Maybe it is because of [core library update to 5.0.0](https://github.com/mapbox/mapbox-gl-native-ios/pull/438), since it mentions changes to how fonts are rasterized.

Starting from Mapbox-iOS-SDK 6.2.0-beta.1 custom fonts are not fetched from our in-house tile server. For RTL text it uses default iOS Arabic font which is rendered garbled/tangled. 
(I know you are under a lot of pressure before iOS 14 release. Appreciate all the effort.)

### Steps to reproduce

 1. Update Mapbox-iOS-SDK to 6.2.0-beta.2
 2. Use this [style JSON](https://pastebin.com/PzK9DSug). This is the style we use in our app. 

### Expected behavior
Text is rendered correctly. This is a screenshot taken from app built with Mapbox-iOS-SDK 6.1.0:
![5](https://user-images.githubusercontent.com/11490764/93362554-592c2880-f85b-11ea-97e2-39b9052c5720.PNG)

### Actual behavior
Text is rendered incorrectly. This is a screenshot taken from app built with Mapbox-iOS-SDK 6.2.0-beta.2:
![6](https://user-images.githubusercontent.com/11490764/93362569-5df0dc80-f85b-11ea-8991-9cfe1a1cc976.PNG)

### Configuration

**Mapbox SDK versions:** 6.2.0-beta.1 & 6.2.0-beta.2 (Font is fetched correctly on 6.1.0)
**iOS/macOS versions:**         iOS 14        | iOS 13.7
**Device/simulator models:**  iPhone X    | iPhone 7
**Xcode version:**                    Xcode 12 GM & Xcode 11.7

**Comment by mohammadZ74** [comment] 2020-09-17 07:26
Same here

**Comment by AliKarami** [comment] 2020-09-17 07:43
Same.
Something is wrong with fonts in the new SDK.

**Comment by emranovin** [comment] 2020-09-17 08:28
ditto

**Comment by mohammadZ74** [comment] 2020-09-17 08:30
I also added example project to clarify the issue:
This is 6.2.0 SDK and as you can see the font are not displaying correctly.
https://github.com/mohammadZ74/MapBoxExample
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-17 at 12 59 52](https://user-images.githubusercontent.com/26526395/93443961-af45ae00-f8e5-11ea-803c-fe576ae5d45e.png)


This is 6.1.0 which fonts are displayed correctly:
https://github.com/mohammadZ74/MapBoxExample/tree/6.1.0
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-17 at 13 00 36](https://user-images.githubusercontent.com/26526395/93444311-c8e6f580-f8e5-11ea-8988-9beb3e8d2f81.png)

**Comment by mohammadZ74** [comment] 2020-09-17 10:10
I did a some network monitoring and realized on 6.2.0 font api is not called.
This is all apis that get called on 6.1.0:
[MapBoxExample_20200917_140732_405-wormholy.txt](https://github.com/mapbox/mapbox-gl-native-ios/files/5238238/MapBoxExample_20200917_140732_405-wormholy.txt)

And this is all apis that get called on 6.2.0:
[MapBoxExample_20200917_140525_746-wormholy.txt](https://github.com/mapbox/mapbox-gl-native-ios/files/5238243/MapBoxExample_20200917_140525_746-wormholy.txt)

**Comment by julianrex** [comment] 2020-09-17 16:34
Thanks for the reports. We're investigating.

**Comment by jmkiley** [comment] 2020-09-17 18:32
Hello all! 

Thank you so much for your patience, helpful reports, and the test case. I tested this out and was able to see the jumbled letters locally. We are continuing to investigate the cause, but have a possible workaround in the mean time.

When I added an `MGLIdeographicFontFamilyName` key to my `Info.plist` containing the fonts from your style, the text renders correctly. Does this seem to work on your end?

<img width="350" alt="Info.plist with fonts specified" src="https://user-images.githubusercontent.com/12474734/93511134-2b84c500-f8d7-11ea-9ae3-71ac08e9e766.png">

 With the Info.plist key | Without the Info.plist key 
 -- | -- |
| <img width="250" src=https://user-images.githubusercontent.com/12474734/93511761-28d69f80-f8d8-11ea-8f6d-9e1fcdd2aa6b.PNG> |  <img width="250" src=https://user-images.githubusercontent.com/12474734/93511752-24aa8200-f8d8-11ea-9cc1-1c62ae97dcbc.PNG> |

**Comment by behdaad** [comment] 2020-09-17 18:36
Thanks Jordan.
Yes it helps with the jumbled text, but still our custom font is not set. What we're seeing is the default iOS SF Arabic font. 

Thanks for your efforts and please let me know if I can help.

**Comment by jmkiley** [comment] 2020-09-17 19:04
@behdaad Thank you! I see what you mean about the fonts. We're continuing to investigate the issue and will keep you posted!

**Comment by julianrex** [comment] 2020-09-17 22:23
FYI we have reverted the core library to `4.0.0` for the upcoming `6.2.0` release. We'll update to `5.0.0` in a subsequent release.

**Comment by behdaad** [comment] 2020-09-18 14:37
A quick update: we managed to use a bundled font by setting the `MGLIdeographicFontFamilyName` key to a locally bundled font name and it worked. However, since we use regular and bold variants of that font in our map, it is not as good-looking as it was before (Please let me know if I've misunderstood the docs, but to my understanding the first font that matches the `MGLIdeographicFontFamilyName` key is used in all the style layers of the map).

Again, thanks for all the hard work. Apple put an enormous pressure on all the dev community by releasing iOS 14 with a 24-hour notice.

**Comment by jmkiley** [comment] 2020-09-18 19:20
Hi @behdaad - 

Thank you! Could you remove the `MGLIdeographicFontFamilyName` from the Info.plist and see if that helps? Since we have reverted the core library, it shouldn't be necessary. 

We appreciate your patience!

**Comment by behdaad** [comment] 2020-09-18 20:45
@jmkiley unfortunately no. You can see for yourself [here](https://github.com/behdaad/Mapbox-iOS14). You can just clone and run the project on the `master` branch. (Thank you @mohammadZ74 for the sample project)
You can also check our [network log](https://github.com/mapbox/mapbox-gl-native-ios/files/5248052/MapBoxExample_20200919_011314_989-wormholy.txt) and see there are no requests to our font APIs.

**Comment by jmkiley** [comment] 2020-09-21 22:02
Hi @behdaad  -

Thank you for your update and your patience. We are currently working on a fix for this issue. In the meantime, we suggest staying on 6.1.0 so that you can continue using your custom fonts. We appreciate the logs and your troubleshooting.

**Closed** 2020-09-23 18:18 UTC
Labels: p0, status: triage
