### ISSUE TITLE
5.8.0 beta 1 - Crash when go back to foreground

### ISSUE THREAD

**Issue by rfremont** [mapbox/mapbox-gl-native-ios#234] opened 2020-03-20 15:55 UTC
With the SDK 5.8.0 beta 1 the SDK crash when the app go back to foreground.
**No crash with the 5.7.0 version**

### Steps to reproduce

 1. Display the map
 2. Put the app in background
 3. Put the app in foreground

### Expected behavior
Map is displayed

### Actual behavior
We have a crash

### Configuration

**Mapbox SDK versions:**  5.8.0 beta 1
**iOS/macOS versions:** iOS 13/12
**Device/simulator models:** iPhone 6 (device- iOS 12) / iPhone 11 simulator (iOS 13)
**Xcode version:** Xcode 11.3.1

Thread crash message:
Thread 11 name:  com.mapbox.mbgl.OnlineFileSource
Thread 11 Crashed:
0   libsystem_kernel.dylib        	0x0000000187b470dc __pthread_kill + 8
1   libsystem_pthread.dylib       	0x0000000187bc0094 pthread_kill$VARIANT$mp + 380
2   libsystem_c.dylib             	0x0000000187a9ff4c __abort + 152
3   libsystem_c.dylib             	0x0000000187a9feb4 __abort + 0
4   libc++abi.dylib               	0x000000018716c788 __cxa_bad_cast + 0
5   libc++abi.dylib               	0x000000018716c91c default_terminate_handler+ 6428 () + 284
6   libobjc.A.dylib               	0x0000000187183e10 _objc_terminate+ 24080 () + 140
7   Manao                         	0x0000000100ed1f24 CLSTerminateHandler+ 6151972 () + 348
8   libc++abi.dylib               	0x0000000187178838 std::__terminate(void (*)+ 55352 ()) + 16
9   libc++abi.dylib               	0x0000000187178434 __cxa_rethrow + 144
10  libobjc.A.dylib               	0x0000000187183bc8 objc_exception_rethrow + 44
11  CoreFoundation                	0x0000000187f37020 CFRunLoopRunSpecific + 544
12  CoreFoundation                	0x0000000187f37d10 CFRunLoopRun + 80
13  Mapbox                        	0x00000001025533a8 mbgl::util::Thread<mbgl::OnlineFileSourceThread>::Thread<std::__1::tuple<> >(std::__1::function<void ()>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::tuple<>&&)::'lambda'()::operator()() + 275368 (thread.hpp:68)
14  Mapbox                        	0x0000000102553268 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mbgl::util::Thread<mbgl::OnlineFileSourceThread>::Thread<std::__1::tuple<> >(std::__1::function<void ()>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::tuple<>&&)::'lambda'()> >(void*) + 275048 (thread:354)
15  libsystem_pthread.dylib       	0x0000000187bc92c0 _pthread_body + 128
16  libsystem_pthread.dylib       	0x0000000187bc9220 _pthread_start + 44
17  libsystem_pthread.dylib       	0x0000000187bcccdc thread_start + 4

**Comment by knov** [comment] 2020-03-24 15:58
Thanks for flagging this for our beta build @rfremont. We will be sure to review the crash before our release.

**Comment by 1ec5** [comment] 2020-03-30 19:28
Does your application use MGLOfflineStorage or MGLMapSnapshotter? In particular, are there any packs downloading or snapshotters snapshotting around the time your application goes into the background or comes into the foreground?

**Comment by rfremont** [comment] 2020-03-30 20:36
No, my application just use custom URL style provided by mapbox studio.

**Comment by 1ec5** [comment] 2020-04-02 14:56
Unfortunately the stack trace only tells us that there was an uncaught exception in some code on the OnlineFileSource thread.

I’m unable to reproduce the issue in an example application by backgrounding and foregrounding the application. Are you able to reproduce this issue consistently? What about in v5.8.0-alpha.1?

**Comment by rfremont** [comment] 2020-04-06 10:29
Issue is 100% reproducible with **5.8.0-beta.1**
Issue does **not** happen with **5.8.0-beta.2**
Issue does **not** happen with **5.8.0-apha.1**

**Comment by 1ec5** [comment] 2020-04-06 15:36
Thanks, based on that timeline, I’m pretty sure this regression was introduced in #188 and fixed in 49011ec1b11856efe1e09bac0a7da137be649209 for #242.

**Closed by 1ec5** 2020-04-06 15:36 UTC
Labels: status: triage
