### ISSUE TITLE
Force offline when actually connected?

### ISSUE THREAD

**Issue by kostiag** [mapbox/mapbox-gl-native-ios#309] opened 2020-05-22 15:25 UTC
Not a bug, perhaps a feature request or instruction help?
Is it possible to force offline mode even when connected?

**Comment by JesseCrocker** [comment] 2020-07-16 21:47
I've implemented this in a fork. https://github.com/trailbehind/mapbox-gl-native-ios/pull/1  If there is some chance it might be accepted i'll open a PR to this repo.

**Comment by julianrex** [comment] 2020-08-14 15:27
This is a duplicate of https://github.com/mapbox/mapbox-gl-native-ios/issues/217, which references an older PR from before our repo transition. We need to consider `MGLMapSnapshotter` too, rather than just `MGLMapView`. 

I'm going to close this issue as as dupe.

**Closed by julianrex** 2020-08-14 15:27 UTC
Labels: status: triage
