### ISSUE TITLE
Request: Allow installation via Swift Package Manager in addition to Cocoapods/Carthage

### ISSUE THREAD

**Issue by klundberg** [mapbox/mapbox-gl-native-ios#490] opened 2020-09-30 18:52 UTC
Hello!
Now that Xcode 12 is out and allows for binary dependencies to be installed and managed with Swift Package Manager, is there a plan to allow developers to integrate the mapbox sdk using SwiftPM? I'd love to be able to do this, since the apps I'm working on only have a few more dependencies managed with cocoapods, and I'd love to be able to centralize on SwiftPM completely soon. Thanks!

**Comment by Yaacoub** [comment] 2020-10-18 15:59
Any updates in regards to making the SDK available via Swift Package Manager?

**Comment by KaneCheshire** [comment] 2020-10-25 16:13
It would be great to see this happen. Is there anything missing from SPM that would stop this being possible now? Anything the community can do to help? My project is 100% SPM now and looking to add MapBox so was a bit sad to see I'll need to revert to something else just for this.

**Comment by 1ec5** [comment] 2020-11-11 09:27
Duplicate of #546.

**Closed by 1ec5** 2020-11-11 09:27 UTC
Labels: status: triage
